# Generated by Django 3.2.22 on 2024-01-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('specifications', models.TextField()),
                ('reviews', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='cake_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='bakery_model',
        ),
    ]
